---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "users.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
