---
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{include "api-gateway.fullname" . }}
spec:
  minAvailable: {{.Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{include "api-gateway.name" . }}
{{- end }}
