{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orders.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "orders.name" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
{{ toYaml .Values.ingress.rules | indent 4 }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
